### ISSUE TITLE
feat：增加对 mdx 的支持

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/website#11]
目前支持 `.md`，希望后续增加对 `.mdx` 的支持。

https://www.mdxjs.cn/

**Comment by tisonkun** [comment]
为什么呢？我理解只在你写了 mdx 的文件以后，这才是个依赖。否则只是适配一阵，其实又不用上。比起【增加对 mdx 的支持】一个用上 mdx 的 idea 倒推出要增加对 mdx 的支持会合适一点。

**Comment by LinuxSuRen** [comment]
嗯，可以罗列下 MD 不满足的需求，然后再看看有哪些备选项。`mdx` 可能是其中一个不错的方案。

**Comment by stevending1st** [comment]
> 为什么呢？我理解只在你写了 mdx 的文件以后，这才是个依赖。否则只是适配一阵，其实又不用上。比起【增加对 mdx 的支持】一个用上 mdx 的 idea 倒推出要增加对 mdx 的支持会合适一点。

`md` 似乎无法插入音频，所以希望增加相关支持。
每期节目可以在网页端收听。

**Comment by LinuxSuRen** [comment]
> 每期节目可以在网页端收听。

@MikeyWei 提到过，在网页上提供收听音频可能会有潜在的合规风险。

**Comment by stevending1st** [comment]
> 在网页上提供收听音频可能会有潜在的合规风险。

是托管平台限制吗？

**Comment by LinuxSuRen** [comment]
> 是托管平台限制吗？

提供音视频服务的话，需要相关许可证。

**Comment by sxzz** [comment]
md 支持一切 HTML 标签，甚至支持内嵌 Vue 组件，所以没有必要写 mdx。

**Comment by tisonkun** [comment]
@sxzz 确实，这是 Vue...MDX 我用起来还是跟 JSX 结合比较爽。

**Comment by stevending1st** [comment]
Thanks
