### ISSUE TITLE
ui: increase the title's font-weight to emphasize it

### ISSUE THREAD

**Issue by imentu** [opensource-f2f/website#15]
I think increasing the title's font weight of each episode can increase the readability.
as here, I set the title's font-weight to 600 and compare the result to the original.

### Before

![image](https://user-images.githubusercontent.com/62298214/192087798-5f7c018b-980b-4dfa-be36-3ff54982aa90.png)

### After

![image](https://user-images.githubusercontent.com/62298214/192087805-d5f1b039-d266-45cd-a1c9-73afb64efc66.png)

### Before

![image](https://user-images.githubusercontent.com/62298214/192087814-fc0fc546-6b16-42a7-8142-4b9d875402a0.png)

### After

![image](https://user-images.githubusercontent.com/62298214/192087819-7e707370-db2e-4a14-95d8-1fefe8120d8a.png)

**Comment by sxzz** [comment]
Did you open the page on Windows? What font do you use?

It's bold on my machine (macOS and PingFang SC)

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/6481596/192088985-5f1a729f-a91c-4464-ad23-bd685e1f39d5.png">

**Comment by imentu** [comment]
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎28-‎Jun-‎2022
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

![image](https://user-images.githubusercontent.com/62298214/192089417-be64f328-802c-475c-8fab-096266e61fae.png)

**Comment by sxzz** [comment]
Maybe there's no 500-bold variant font in Microsoft YaHei... 🤔 But I think 700 is too bold

**Comment by imentu** [comment]
Maybe 600 is ok?

**Comment by sxzz** [comment]
There's no 600-bold font in both Mac and Windows, so it will display 700 in fallback.

![image](https://user-images.githubusercontent.com/6481596/192089671-4615b43f-c62e-447b-9107-6e0d31aa50a9.png)
