### ISSUE TITLE
在首页显著位置添加 RSS 订阅按钮

### ISSUE THREAD

**Issue by MikeyWei** [opensource-f2f/website#18]
目前在首页上没有露出订阅入口，建议在首页右上角或logo附近位置，添加一个 RSS 订阅按钮，并链接到 https://www.ximalaya.com/album/53320813.xml

**Comment by sxzz** [comment]
OK 稍后添加

**Comment by LinuxSuRen** [comment]
也可以考虑在 10 月份做这个 issue，顺便参与这个活动 https://hacktoberfest.digitalocean.com/
