### ISSUE TITLE
在首页Banner位置增加“成员邮箱”入口

### ISSUE THREAD

**Issue by MikeyWei** [opensource-f2f/website#34]
建议在首页 Banner 区域的“GitHub、Twitter、Youtube、RSS“位置增加一个项目成员官方邮箱的入口，并将链接指向 https://mail.osf2f.net
方便项目成员有需要登录邮箱时，不必再记官方域名邮箱的服务方及入口地址。

**Comment by LinuxSuRen** [comment]
考虑到拥有“成员邮箱”的人数可能远少于访问官网的游客数量，是不是可以把这个入口放到页面底部呢
