### ISSUE TITLE
Maintaince error: unable to update the website

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/website#60]
hi @sxzz, the website update action failed with 4 retry. Would you mind help us taking  a look at it? Thanks.

https://github.com/opensource-f2f/episode/actions/runs/6438577513/job/17485327909

**Comment by wey-gu** [comment]
hmmm... maybe not format issues? need vercel project access to see the build failure reason T__T

**Comment by LinuxSuRen** [comment]
It is possible the issue comes from the Vercel project.

**Comment by wey-gu** [comment]
> It is possible the issue comes from the Vercel project.

Probably yes, or some minor format issues that I couldn't figure out.

Let's see if zz got some bandwidth to take a look.

In case not, let's fully revert master to a working hash to exclude the format first and see next move

**Comment by sxzz** [comment]
The date is missing in `S04E00`. We should fix it in https://github.com/opensource-f2f/episode repo

**Comment by LinuxSuRen** [comment]
Fixed the data field in https://github.com/opensource-f2f/episode/commit/6428fea5772d87bf1f93ff772d50977cc731d9fc

Do you know how we could see the error log? And we might need to do the fields validation check.

> Sorry forget creating a PR on this.

**Comment by LinuxSuRen** [comment]
It works now. Thanks @sxzz
