### ISSUE TITLE
添加 AI 小助手的链接

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/website#62]
下面是定制过的 AI 助手：

* [智谱清言](https://chatglm.cn/main/gdetail/65d70a301e6bc1f647c934e3)

**Comment by xiaowangxiaowang256256** [comment]
解决方案参考
1、网站首页，添加一个 AI小助手图片
![777](https://github.com/opensource-f2f/website/assets/111274524/89527889-9246-4fea-b12d-d6936e3fb8cd)
2、点击图片跳转至[智谱清言](https://chatglm.cn/main/gdetail/65d70a301e6bc1f647c934e3)，
![77](https://github.com/opensource-f2f/website/assets/111274524/f0b781e8-68d8-4e30-aa2b-c3d37c345f47)
3、存在问题：用户注册登录智谱清言后，才能进行查看
![image](https://github.com/opensource-f2f/website/assets/111274524/d86d20a5-3777-48ba-9c22-2bf636ff41b7)

**Comment by LinuxSuRen** [comment]
有一个疑问，您这里的图片是从哪里来的？是否有版权？如果没有版权授权的话，可以考虑找个免费版权授权的，或者自行画一个，再或者直接一个超链接文字也可以。

**Comment by xiaowangxiaowang256256** [comment]
[图片来源](https://mastergo.com/community/resource/9252?from=card)，版权协议为[知识共享 - 署名 4.](https://creativecommons.org/licenses/by/4.0/)，可商用

**Comment by LinuxSuRen** [comment]
有版权，那太好了。
