### ISSUE TITLE
建议：网站 百度搜索引擎 SEO优化

### ISSUE THREAD

**Issue by xiaowangxiaowang256256** [opensource-f2f/website#71]
**现状描述：**
面对潜在的，来自中文社区的《开源面对面》用户，当他们使用百度搜索引擎，搜索关键词 “开源面对面”时，[百度搜索结果](https://www.baidu.com/s?ie=UTF-8&wd=%E5%BC%80%E6%BA%90%E9%9D%A2%E5%AF%B9%E9%9D%A2)是没有网站信息的。

**期望结果：**
搜索结果中第1页第1个搜索结果，展示出 [开源面对面官网](https://osf2f.net/) 的 网站信息

**参考：**
1、[元岛官网](https://www.midorg.com/)的 [百度搜索结果](https://www.baidu.com/s?ie=UTF-8&wd=%E5%85%83%E5%B2%9B)
2、网站管理者，可通过官方渠道[百度搜索资源平台](https://ziyuan.baidu.com/site/index)，对网站进行管理认证
![image](https://github.com/opensource-f2f/website/assets/111274524/1e6492a2-9f62-4a5d-b316-2bccfabc6e0a)

**Comment by LinuxSuRen** [comment]
我之前提交过，但没啥效果。有个问题是，我们这个网站好像没有 sitemap 可供爬虫收录。

**Comment by xiaowangxiaowang256256** [comment]
> 我之前提交过，但没啥效果。有个问题是，我们这个网站好像没有 sitemap 可供爬虫收录。

好嘞。
1、我之前理解的是只要将网站提交上去就能排到第1页第1位。看来肤浅了。
2、关于 sitemap 爬虫收录，我也去了解一下，然后再去看看 [元岛官网](https://www.midorg.com/)的优化细节，看看它是如何做到排到第1页第1位的。

**Comment by LinuxSuRen** [comment]
对官网在百度站点中数据感兴趣的朋友，可以私下把你的百度账号发给我（WX与GitHub同ID），把你加入进去。

**Comment by xiaowangxiaowang256256** [comment]
> 对官网在百度站点中数据感兴趣的朋友，可以私下把你的百度账号发给我（WX与GitHub同ID），把你加入进去。

站点任务 认领完成，任务目标：
搜索结果中第1页第1个搜索结果，展示出 [开源面对面官网](https://osf2f.net/) 的 网站信息

**Comment by LinuxSuRen** [comment]
@xiaowangxiaowang256256  如果你有相对完整的想法的话，可以考虑作为导师，把 Proposal 提交到[开源之夏](https://summer-ospp.ac.cn/)活动中交给学生来做。

**Comment by xiaowangxiaowang256256** [comment]
> @xiaowangxiaowang256256 如果你有相对完整的想法的话，可以考虑作为导师，把 Proposal 提交到[开源之夏](https://summer-ospp.ac.cn/)活动中交给学生来做。

当前目标很明确。具体实践方法还需要补充。
这是一个不错的提议。我可以尝试这样做一下。

**Comment by LinuxSuRen** [comment]
已经收录10个页面，但百度似乎并没有把“开源面对面”这个关键字和网站联系起来，甚至前5页都没有。

![image](https://github.com/opensource-f2f/website/assets/1450685/f1105f1b-ebb3-4b16-b62f-8c91880f97c6)
![image](https://github.com/opensource-f2f/website/assets/1450685/75eb0179-4bc1-4975-b185-356e6ccdc75b)

**Comment by xiaowangxiaowang256256** [comment]
是的，我主要是 对标[元岛官网](https://www.baidu.com/s?ie=utf8&wd=%E5%85%83%E5%B2%9B)的SEO，如果单纯以网站收录，它的[网站收录只有7个](https://www.baidu.com/s?ie=utf8&wd=site:%20www.midorg.com)。现在还没找到优化方向。

**Comment by LinuxSuRen** [comment]
下面是来自 Google Analytics 的流量统计

![image](https://github.com/opensource-f2f/website/assets/1450685/008084c1-8ddc-47b8-a694-62137db84411)
![image](https://github.com/opensource-f2f/website/assets/1450685/8093920f-1f3b-4ef7-8192-6befce50f433)
![image](https://github.com/opensource-f2f/website/assets/1450685/d400027c-d3bc-43e7-9ff8-6fd0f908b556)
